-- Enable RLS on all application tables.
-- The postgres/service_role user bypasses RLS automatically (no policies needed).
-- anon and authenticated Supabase roles are blocked from direct access.

ALTER TABLE "Usuario" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Cliente" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Contrato" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Cuota" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Pago" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ModificacionContrato" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CasoLegal" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AplicacionPago" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SistemaExterno" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExternalReference" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "IntegrationEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExternalSyncLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ClienteContacto" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ClienteFacturacion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ClientImportBatch" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ClientImportItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ContractImportItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InstallmentImportItem" ENABLE ROW LEVEL SECURITY;
